Use dom4 instead of dom-polyfills polyfill NPM package
The dom-polyfills library seems unmaintained, and has seen little
usage. Users of IE11 got an error related to the polyfill:

   Error: Object.defineProperty: argument is not an Object

We fix this issue by replacing dom4 with the more mainstream dom4
polyfills package.